# Generated by Django 4.2.1 on 2023-09-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('name', models.SlugField(choices=[('clothing', 'Одежда'), ('electronics', 'Электроника'), ('other', 'Разное')], max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_session', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.packagetype')),
            ],
        ),
    ]
